Added ChatGptService and AIResponseParser Class from TJ-Bot
Together-Java/TJ-Plays pull request #18
Opened 2024-03-16 18:18 UTC by Suleman70

**Integrating ChatGPT to TJ-Plays**

I added the ChatGptService and AIResponseParser class from the TJ-Bot to TJ-Plays and also added its dependencies.

**TODO:** We need to come up with a way of making sure there is only one instance of this class - and that it can be shared among other classes.

2024-03-16 19:48 UTC, Taz03 requested changes

2024-03-16 19:48 UTC, Taz03 commented on app/src/main/java/com/togetherjava/tjplays/services/chatgpt/ChatGptService.java
this is not the latest file use the current [ChatGptService](https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/features/chatgpt/ChatGptService.java)

2024-03-16 19:48 UTC, Taz03 commented on app/src/main/java/com/togetherjava/tjplays/services/chatgpt/AIResponseParser.java
This is not in TJ-Bot codebase

2024-03-16 19:48 UTC, Taz03 requested changes

2024-03-16 19:48 UTC, Taz03 commented on app/src/main/java/com/togetherjava/tjplays/services/chatgpt/AIResponseParser.java
> + * This class is from the TJ-Bot repository: <a href="https://github.com/Together-Java/TJ-Bot">...</a>
dont

2024-03-16 19:48 UTC, Taz03 commented on app/src/main/java/com/togetherjava/tjplays/services/chatgpt/ChatGptService.java
> + * This class is from the TJ-Bot repository: <a href="https://github.com/Together-Java/TJ-Bot">...</a>
dont

2024-03-16 20:04 UTC, Suleman70 commented
Added the changes @Taz03

2024-03-16 20:29 UTC, Taz03 requested changes

2024-03-16 20:29 UTC, Taz03 commented on app/src/main/java/com/togetherjava/tjplays/Bot.java
revert the changes of this file

2024-03-16 20:29 UTC, Taz03 commented on app/src/main/java/com/togetherjava/tjplays/services/chatgpt/ChatGptService.java
> +                rewriting the code. DON'T supply a corrected version of the code.\s""");
we dont need this, in this project so remove it

2024-03-16 20:29 UTC, Taz03 commented on app/src/main/java/com/togetherjava/tjplays/services/chatgpt/ChatGptService.java
> +                    .formatted(context, instructions, question);
we dont need these instructions

2024-03-16 20:29 UTC, Taz03 commented on app/build.gradle
> +    runtimeOnly 'org.apache.logging.log4j:log4j-slf4j18-impl:2.18.0'
add new lines in between

2024-03-16 22:49 UTC, Taz03 submitted a review, later dismissed

2024-03-17 01:00 UTC, Taz03 approved these changes

2024-03-17 01:00 UTC, merged